# Generated by Django 3.1.1 on 2021-05-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_xp', models.IntegerField(default=0)),
                ('charity', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Company details',
                'verbose_name_plural': 'Company details',
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_sub', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('company_id', models.IntegerField()),
                ('week', models.IntegerField()),
                ('user_xp', models.IntegerField(default=0)),
                ('user_level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'User details',
                'verbose_name_plural': 'User details',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10)),
                ('company_id', models.IntegerField()),
                ('answer0', models.CharField(blank=True, max_length=2)),
                ('answer1', models.CharField(blank=True, max_length=2)),
                ('answer2', models.CharField(blank=True, max_length=2)),
                ('answer3', models.CharField(blank=True, max_length=2)),
                ('answer4', models.CharField(blank=True, max_length=2)),
                ('answer5', models.CharField(blank=True, max_length=2)),
                ('answer6', models.CharField(blank=True, max_length=2)),
                ('answer7', models.CharField(blank=True, max_length=2)),
                ('answer8', models.CharField(blank=True, max_length=2)),
                ('answer9', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'User feedback',
                'verbose_name_plural': 'User feedback',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('partial', models.CharField(blank=True, default='', max_length=40)),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapi.userdetails')),
            ],
            options={
                'verbose_name': 'Task progress',
                'verbose_name_plural': 'Task progress',
                'ordering': ['task_id'],
            },
        ),
    ]
