# Generated by Django 3.1.1 on 2021-06-03 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 6, 3)),
        ),
    ]
